version: "3.8"
services:
  latest:
    image: ${REG_HOST}/node-lts:latest
    build:
      context: .
      target: latest
  bring-it:
    image: ${REG_HOST}/node-lts:bring-it
    build:
      context: .
      target: bring-it
  imagemin:
    image: ${REG_HOST}/node-lts:imagemin
    build:
      context: .
      target: imagemin
  python3:
    image: ${REG_HOST}/node-lts:python3
    build:
      context: .
      target: python3
  playwright:
    image: ${REG_HOST}/node-lts:playwright
    build:
      context: .
      target: playwright
  deploy:
    image: ${REG_HOST}/node-lts:deploy
    build:
      context: .
      target: deploy
  browser:
    image: ${REG_HOST}/node-lts:browser
    build:
      context: .
      target: browser