services:
  browser:
    image: ${REG_HOST}/node-lts:browser
    build:
      dockerfile: conf/playwright.dockerfile
      context: .
      target: browser    
  sample:
    image: ${REG_HOST}/node-lts:sample
    build:
      dockerfile: conf/playwright.dockerfile
      context: .
      target: sample
