name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/description.yml
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: airkro
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: airkro/node-lts
          short-description: ${{ github.event.repository.description }}
