name: Push Playwright

on:
  push:
    branches:
      - master
    paths:
      - conf/playwright.dockerfile
      - docker-compose.yml
      - .github/workflows/playwright.yml
  workflow_dispatch:

jobs:
  PushToDockerHub:
    runs-on: ubuntu-latest
    env:
      REG_HOST: airkro
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: airkro
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        run: docker compose build

      - name: Push
        run: docker compose push
